# Based on https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  pypi-publish:
    name: upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

