# Based on https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: release_testpypi

on:
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish-to-testpypi:
    name: upload release to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release_testpypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
